spring:
  application:
    name: colados-leaderboard-api
  flyway:
    enabled: true
  config:
    import: optional:file:.env[.properties]

  # Database configuration:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # RabbitMQ configuration
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

# Minio configuration
minio:
  url: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME}
  secure: ${MINIO_SECURE}

# RabbitMQ queues, exchanges, and routing keys
rabbitmq:
  queue-img-submitted: ${RABBITMQ_QUEUE_IMG_SUBMITTED}
  exchange-img-submitted: ${RABBITMQ_EXCHANGE_IMG_SUBMITTED}
  routing-key-img-submitted: ${RABBITMQ_ROUTING_KEY_IMG_SUBMITTED}
  queue-img-processed: ${RABBITMQ_QUEUE_IMG_PROCESSED}
  exchange-img-processed: ${RABBITMQ_EXCHANGE_IMG_PROCESSED}
  routing-key-img-processed: ${RABBITMQ_ROUTING_KEY_IMG_PROCESSED}

# Constants
app:
  constants:
    game-max-score: 60
